name: Build
on: push

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: jetpack-joyride
  PROJECT_PATH: .

jobs:
  build-test:
    name: Build and Test 
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:mono-4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Build Generic
        run: |
          godot --headless --build-solutions --quit --import --path $PWD
      - uses: MikeSchulze/gdunit4-action@v1
        with:
          godot-version: ${GODOT_VERSION}
          godot-net: true
          dotnet-version: net9.0
          paths: 'res://UnitTests'
          arguments: '--verbose'
          publish-report: false
  export-windows:
    name: Windows Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:mono-4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          apt-get update
          apt-get install -y xvfb
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-debug "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows