name: "Deploy"

on: 
  push:
    branches: [ 'release' ]

env:
  ITCH_USERNAME: brige
  ITCH_GAME_ID: jumpingjetpacks
jobs:
  deploy:
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
    runs-on: ubuntu-latest
    name: Deploy Itch ${{ matrix.template }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.channel }}
          path: build/${{ matrix.channel }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/${{ matrix.template }}
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
